### ISSUE TITLE
keep getting 403 'forbidden' 'Request not allowed' when trying demo

### ISSUE THREAD

**Issue by KolvacS-W** [anthropics/anthropic-sdk-typescript#457] opened 2024-07-02 10:05 UTC
Hello, I am a tier1 user and successfully tried to use model at workbench:
<img width="1180" alt="Screen Shot 2024-07-02 at 5 57 31 PM" src="https://github.com/anthropics/anthropic-sdk-typescript/assets/55591358/1a683f39-f8f1-4707-bb6e-997119b86d68">

However, when I try to create a ts server to call Claude API, I keep having forbidden error.

I also tried to use the demo:

```typescript
#!/usr/bin/env -S npm run tsn -T

import Anthropic from '@anthropic-ai/sdk';

const client = new Anthropic({
    apiKey: 'my_key',
}); 

console.log(client.apiKey)

async function main() {
  const result = await client.messages.create({
    messages: [
      {
        role: 'user',
        content: 'Hey Claude!?',
      },
    ],
    model: 'claude-3-5-sonnet-20240620',
    max_tokens: 1024,
  });
  console.dir(result);
}

main();
```

But I still get 403 error: 
```
PermissionDeniedError: 403 {"error":{"type":"forbidden","message":"Request not allowed"}}

{status: 403,
  headers: {
    'cf-ray': '89cdc7d74e3e2512-SJC',
    connection: 'keep-alive',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    date: 'Tue, 02 Jul 2024 09:59:01 GMT',
    server: 'cloudflare',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding'
  },
  error: { error: { type: 'forbidden', message: 'Request not allowed' } }
}
```
I also printed out checked my API key to check it is correctly placed. I also tried changing IP address from US to Australia but it didn't help too.

Anybody knows why this would happen? Thanks

**Comment by KC-Zhang** [comment] 2024-07-05 10:12
please fix. same problem here. Curl and python sdk both work

**Comment by dgellow** [comment] 2024-07-05 14:21
Hi, I am not able to reproduce the issue and that feels like a problem on Anthropic side.
The demo example does authenticate correctly as far as I can tell.

Could you try the following from the root of the repository:
- delete the `node_modules` directory
- run `scripts/bootstrap`
- run `scripts/build`
- then run `ANTHROPIC_API_KEY=<your key> ./examples/demo`

If you're still facing the same problem, please reach out to Anthropic support with details to help them figure out why requests sent with API Key are rejected.

**Comment by rattrayalex** [comment] 2024-07-06 22:00
I'm going to go ahead and close this issue because it seems more likely to be a problem with your API key than the SDK. If you're able to share repro steps of using the same `ANTHROPIC_API_KEY` environment variable in both the Python & Node SDK, and the request only fails in the Node SDK, we can reopen.

**Closed as not planned by rattrayalex** 2024-07-06 22:00 UTC

**Comment by 21121995q** [comment] 2025-01-12 12:37
U need to enable vpn, if you are in a country that Claude does not support.

**Comment by heguangyue** [comment] 2025-04-27 06:53
#### use proxy
`from anthropic import Anthropic
import httpx
import os


custom_client = httpx.Client(
    transport=httpx.HTTPTransport(
        proxy=httpx.Proxy(
            url="http://ip:port"
        )
    ),
    timeout=30.0
)

if not os.getenv("ANTHROPIC_API_KEY"):
    print("api_key not found")

client = Anthropic(
    api_key=os.getenv("ANTHROPIC_API_KEY"),
    http_client=custom_client
)



#client.models.list(limit=20);

response = client.messages.create(
    model="claude-3-5-sonnet-20240620",
    messages=[
        {
            "role":"user",
            "content":"Hello, please introduce yourself"
        }
    ],
    max_tokens=400
)

print(response.content[0].text)`
