### ISSUE TITLE
Does Anthropic have any SDKs that can enable uploading attachments and then chatting?

### ISSUE THREAD

**Issue by Minweiwangaaaa** [anthropics/anthropic-sdk-typescript#60] opened 2023-07-13 06:13 UTC
Does Anthropic have any SDKs that can enable uploading attachments and then chatting?

**Comment by rattrayalex** [comment] 2023-07-13 22:05
Closing as a duplicate of https://github.com/anthropics/anthropic-sdk-python/issues/69

**Closed as not planned** 2023-07-14 04:04 UTC
